# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: self-hosted
    env:
      server: ./backend
      client: ./frontend
      variables: ./.github/actions/env.txt
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with: 
          clean: 'false'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install server
        run: yarn install
        working-directory: ${{ env.server }}
      - name: Npm install client
        run: yarn install
        working-directory: ${{ env.client }}
      - name: Build the client
        run: yarn run build --if-present
        working-directory: ${{ env.client }}
        env:
          CI: false
      # - run: npm test --if-present
      #   working-directory: ${{ env.server }}
      - name: Restart the server
        run: |
          pm2 stop 3
          pm2 start 3
          pm2 save
          sudo service nginx restart
        working-directory: ${{ env.server }}
        # env:
        #   CI: false